---
title: "Video ratings"
format: html
---

<p>This file contains all the analyses for the video ratings task.</p>
<p>During this task, participants rated the valence, arousal, fear and disgust of 10 videos from Cowen and Keltner (2017). This was done <b>both before and after</b> the reversal learning task.</p>
<p>For each participant, the 'best' pair of fear and disgust videos (see paper for equation used to determine the 'best' pair) was selected prior to the reversal learning task. This pair were then used as punishments in the reversal learning task for the fear and disgust feedback-type blocks.</p>
<p> Analyses here <b>only look at the individually selected video pair</b> for each participant.</p>
<br>
<p>Additionally, after the points block (which doesn't use the Cowen and Keltner videos), each participant was asked to rate the valence, arousal, fear and disgust they felt when they lost points.</p>
<p>Analysis of these responses is also detailed here.</p>
<br>
<p>This notebook contains</p>
<li>Analysis of ratings of the selected Cowen and Keltner videos to identify any differences in valence, arousal and habituation between the two stimulus types (models A and B).
<li>Analysis of ratings of the selected Cowen and Keltner videos to validate that fear and disgust was sucessfully induced (models C and D)
<li>Analysis of the points ratings (in comparison to timepoint 1 of the selected videos) to assess how the points feedback differed from the fear and disgust feedback
<li>Visualisation of these results
<p></p>

<br>
<h3>Step 1: load in packages and data</h3>
```{python}
#| label: Python packages
#| echo: true
#| code-fold: true
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import jsonlines
from functools import reduce
import statistics
import scipy.stats
import seaborn as sns
import math
import os
import json
import ast
import matplotlib.patches as mpatches
import statsmodels.api as sm
import statsmodels.formula.api as smf
from numpy import std, mean, sqrt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

chosen_stim_df = pd.read_csv("U:/Documents/Disgust learning project/github/disgust_reversal_learning-final/csvs/chosen_stim_excluded.csv")
chosen_stim_df.drop('Unnamed: 0', axis="columns", inplace=True)
```

<h3>Step 2: create long-form data frame</h3>
```{python}
#| label: long-form df
#| echo: true
long_chosen_stim_df=pd.DataFrame()
for i in chosen_stim_df.index:
    row=chosen_stim_df.loc[i]
    #timepoint=['unpleasan']
    timepoint_1=pd.DataFrame({
    'participant_no': [row.participant_no],
    'age': [row.prolific_age],
    'sex': [row. prolific_sex],
    'Vid': [str(row['Vid'])],
    'trial_type': [row.trial_type],
    'Valence': [row.unpleasant_1],
    'Arousal': [row.arousing_1],
    'Fear': [row.frightening_1],
    'Disgust': [row.disgusting_1],
    'Timepoint': 1.0
    })
    timepoint_2=pd.DataFrame({
        'participant_no': [row.participant_no],
        'age': [row.prolific_age],
        'sex': [row. prolific_sex],
        'Vid': [str(row['Vid'])],
        'trial_type': [row.trial_type],
        'Valence': [row.unpleasant_2],
        'Arousal': [row.arousing_2],
        'Fear': [row.frightening_2],
        'Disgust': [row.disgusting_2],
        'Timepoint': 2.0
    })
    long_chosen_stim_df_row=pd.concat([timepoint_1, timepoint_2])
    long_chosen_stim_df=pd.concat([long_chosen_stim_df_row, long_chosen_stim_df])
    long_chosen_stim_df=long_chosen_stim_df[long_chosen_stim_df.trial_type!="points"]
```

<h3>Step 3: Assess the valence, arousal, disgust and fear ratings of the fear and disgust videos used in the reversal learning task</h3>
<p> Do this using 4 mixed effects models - testing effect of timepoint and stimulus type on ratings </p>
<p>List of models to run:
<li>Model A- 'Valence ~ trial_type*Timepoint'
<li>Model B- 'Arousal ~ trial_type*Timepoint'
<li>Model C- 'Disgust ~ trial_type*Timepoint'
<li>Model D- 'Fear ~ trial_type*Timepoint'
<p></p>
<br>
<br>
<p>Before running the models, we can visualise this data:</p>
```{python}
#| echo: true
#| code-fold: true
fig, axes = plt.subplots(2,4, sharex='col', sharey='col')
#title="Ratings of videos used in reversal learning task"
#plt.suptitle(title, fontsize=30)
#plt.suptitle(title)
fig.tight_layout(pad=0.5)
#fig.set_size_inches(10, 5)

palette = {'fear': 'blue',
            'disgust': 'green'}
#sns.stripplot(data=long_chosen_stim_df, ax=axes[0,0], x='Timepoint', y='Valence', hue='trial_type', dodge=True, palette=palette)
sns.barplot(data=long_chosen_stim_df, ax=axes[0,0], x='Timepoint', y='Valence', hue='trial_type', fill=True, palette=palette, linewidth=1)
axes[0,0].get_legend().set_visible(False)
axes[0,0].set_title("Valence rating", fontsize=15) 

sns.pointplot(data=long_chosen_stim_df, ax=axes[1,0], x='Timepoint', y='Valence', hue='trial_type', dodge=True, palette=palette)
axes[1,0].get_legend().set_visible(False)
axes[1,0].xaxis.get_label().set_fontsize(15)

#sns.stripplot(data=long_chosen_stim_df, ax=axes[0,1], x='Timepoint', y='Arousal', hue='trial_type', dodge=True, palette=palette)
sns.barplot(data=long_chosen_stim_df, ax=axes[0,1], x='Timepoint', y='Arousal', hue='trial_type', fill=True, palette=palette, linewidth=1)
axes[0,1].get_legend().set_visible(False)
axes[0,1].set_title("Arousal rating", fontsize=15) 

sns.pointplot(data=long_chosen_stim_df, ax=axes[1,1], x='Timepoint', y='Arousal', hue='trial_type', dodge=False, palette=palette)
axes[1,1].get_legend().set_visible(False)
axes[1,1].xaxis.get_label().set_fontsize(15)

#sns.stripplot(data=long_chosen_stim_df, ax=axes[0,2], x='Timepoint', y='Fear', hue='trial_type', dodge=True, palette=palette)
sns.barplot(data=long_chosen_stim_df, ax=axes[0,2], x='Timepoint', y='Fear', hue='trial_type', fill=True, palette=palette, linewidth=1)
axes[0,2].get_legend().set_visible(False)
axes[0,2].set_title("Fear rating", fontsize=15) 

sns.pointplot(data=long_chosen_stim_df, ax=axes[1,2], x='Timepoint', y='Fear', hue='trial_type', dodge=False, palette=palette)
axes[1,2].get_legend().set_visible(False)
axes[1,2].xaxis.get_label().set_fontsize(15)

#sns.stripplot(data=long_chosen_stim_df, ax=axes[0,3], x='Timepoint', y='Disgust', hue='trial_type', dodge=True, palette=palette)
sns.barplot(data=long_chosen_stim_df, ax=axes[0,3], x='Timepoint', y='Disgust', hue='trial_type', fill=True, palette=palette, linewidth=1)
axes[0,3].get_legend().set_visible(False)
axes[0,3].set_title("Disgust rating", fontsize=15) 

sns.pointplot(data=long_chosen_stim_df, ax=axes[1,3], x='Timepoint', y='Disgust', hue='trial_type', dodge=False, palette=palette)
axes[1,3].get_legend().set_visible(False)
axes[1,3].xaxis.get_label().set_fontsize(15)

plt.figlegend(loc='center left', bbox_to_anchor=(0,1),  handles=[mpatches.Patch(facecolor='blue'), mpatches.Patch(facecolor='green')], labels=['Fear stimulus', 'Disgust stimulus'])
#handles=[mpatches.Patch(facecolor='blue'), mpatches.Patch(facecolor='green')], labels=['Fear stimulus', 'Disgust stimulus'], prop={'size':15})
plt.show()
```

<br>
<br>
<p><b>MODEL A: VALENCE ~ TRIAL_TYPE*TIMEPOINT</b></p>
<p>In this case, the basic model with a by-participant random slope, but no random intercepts or additional covariates produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: disgust videos had a more negative valence than fear (this was <b>counter to prediction</b>)
<li>It also revealed a trial-type*timepoint interaction: valence ratings for disgust didn't change as much over time relative to fear (i.e., disgust is resistant to habituation).
<p></p>
```{python}
#| label: Model A
#| echo: true

data=long_chosen_stim_df.reset_index()
data.replace(['disgust', 'fear'], [1.0,2.0], inplace=True)
formula = 'Valence ~ trial_type*Timepoint'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop', re_formula='~trial_type')
results=model.fit(reml=False)
print(results.summary())
```

<br>
<p><b>MODEL B: AROUSAL ~ TRIAL_TYPE*TIMEPOINT</b></p>
<p>In this case, the basic model with no by-participant random slope, no random intercepts and no additional covariates produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: fear videos had were more arousing than disgust (this was <b>counter to prediction</b>)
<li>There was no trial-type*timepoint interaction (no difference in habituation in the arousal measure)
<p></p>
```{python}
#| label: Model B
#| echo: true

formula = 'Arousal ~ trial_type*Timepoint'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<br>
<p><b>MODEL C: DISGUST ~ TRIAL_TYPE*TIMEPOINT</b></p>
<p>In this case, the  model with a by-participant random slope, but no random intercepts and no additional covariates produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: disgust videos had were more disgusting than fear (this was <b>as predicted</b>)
<li>There was an effect of timepoint (all stimuli got less disgusting over time)
<li>There was a trial-type*timepoint interaction (the disgust ratings for fear and disgust videos changed differentially over time)
<p></p>
```{python}
#| label: Model C
#| echo: true

formula = 'Disgust ~ trial_type*Timepoint'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop', re_formula='~trial_type')
results=model.fit(reml=False)
print(results.summary())
```

<br>
<p><b>MODEL D: FEAR ~ TRIAL_TYPE*TIMEPOINT</b></p>
<p>In this case, the  model with a by-participant random slope, but no random intercepts and no additional covariates produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: disgust videos had were more disgusting than fear (this was <b>as predicted</b>)
<li>There was an effect of timepoint (all stimuli got less disgusting over time)
<li>There was a trial-type*timepoint interaction (the disgust ratings for fear and disgust videos changed differentially over time)
<p></p>
```{python}
#| label: Model D
#| echo: true

formula = 'Fear ~ trial_type*Timepoint'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop', re_formula='~trial_type')
results=model.fit(reml=False)
print(results.summary())
```

<h3>Step 4: check how points-based feedback differed from disgust and fear-based feedback</h3>
<p> Doing this using 4 mixed effects models - testing the effect of stimulus type on ratings </p>
<p>List of models to run:
<li>Model A- 'Valence ~ trial_type'
<li>Model B- 'Arousal ~ trial_type'
<li>Model C- 'Disgust ~ trial_type'
<li>Model D- 'Fear ~ trial_type'
<p></p>
<p>NB there is only timepoint 1 of fear and disgust ratings are included in this model (as points rating only has one timepoint).</p>
<br>
<br>
<p>Before running the models, we can visualise this data:</p>
```{python}
#| echo: true
#| code-fold: true
data=chosen_stim_df[['participant_no', 'trial_type', 'unpleasant_1', 'arousing_1', 'disgusting_1', 'frightening_1']].sort_values('trial_type')
fig, axes = plt.subplots(2,2)
title="Initial ratings of videos fear, disgust and points videos"
plt.suptitle(title, fontsize=16)
fig.tight_layout(pad=1.5)
fig.set_size_inches(5, 5)

order=['fear', 'disgust', 'points']
palette = {'fear': 'blue',
            'disgust': 'green',
            'points': 'purple'}
sns.barplot(data=data, ax=axes[0,0],   x='trial_type', hue='trial_type', y='unpleasant_1', palette=palette, legend=False, fill=True, linewidth=1, hue_order=order)
#sns.stripplot(data=data, ax=axes[0,0],  x='trial_type', hue='trial_type', y='unpleasant_1', palette=palette, legend=False, dodge=False, hue_order=order)
axes[0,0].set_xlabel('')
axes[0,0].set_ylabel('Valence')

sns.barplot(data=data, ax=axes[0,1], x='trial_type', hue='trial_type', y='arousing_1', palette=palette, legend=False, fill=True, linewidth=1, hue_order=order)
#sns.stripplot(data=data, ax=axes[0,1], x='trial_type', hue='trial_type', y='arousing_1', palette=palette, legend=False, dodge=False, hue_order=order)
axes[0,1].set_xlabel('')
axes[0,1].set_ylabel('Arousal')

sns.barplot(data=data, ax=axes[1,0], x='trial_type', hue='trial_type', y='disgusting_1', palette=palette, legend=False, fill=True, linewidth=1, hue_order=order)
#sns.stripplot(data=data, ax=axes[1,0], x='trial_type', hue='trial_type', y='disgusting_1', palette=palette, legend=False, dodge=False, hue_order=order)
axes[1,0].set_xlabel('')
axes[1,0].set_ylabel('Disgust')

sns.barplot(data=data, ax=axes[1,1], x='trial_type',  hue='trial_type', y='frightening_1', palette=palette, legend=False, fill=True, linewidth=1, hue_order=order)
#sns.stripplot(data=data, ax=axes[1,1], x='trial_type',  hue='trial_type',  y='frightening_1', palette=palette, legend=False, dodge=False, hue_order=order)
axes[1,1].set_xlabel('')
axes[1,1].set_ylabel('Fear')
```

<br>
<br>
<p><b>MODEL E: VALENCE ~ TRIAL_TYPE</b></p>
<p>In this case, the basic model with no by-participant random slope,  no random intercepts but with sex added as a covariate produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: disgust videos had a more negative valence than points (<b>as predicted</b>)
<li>But there was <b>no predicted difference</b> in valence between points and fear
<li>There was also a significant negative effect of age
<p></p>
```{python}
#| label: Model E
#| echo: true

data=chosen_stim_df[['participant_no', 'trial_type', 'unpleasant_1', 'arousing_1', 'disgusting_1', 'frightening_1', 'Vid', 'prolific_age', 'prolific_sex']]
data=data.replace(['points'], ['apoints']) ##makes comparison condition points

formula = 'unpleasant_1~trial_type+prolific_sex'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<p>The effects remain when the sex covariate is removed</p>
```{python}
#| label: Model E no covariates
#| echo: true
formula = 'unpleasant_1~trial_type'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<br>
<br>
<p><b>MODEL F: AROUSAL ~ TRIAL_TYPE</b></p>
<p>In this case, the basic model with no by-participant random slope,  no random intercepts and no additional covariates produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: fear videos were more arousing than points (<b>as predicted</b>)
<li>But there was <b>no predicted difference</b> in arousal between points and disgust
<p></p>
```{python}
#| label: Model F
#| echo: true

formula = 'arousing_1~trial_type'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<p><b>MODEL G: DISGUST ~ TRIAL_TYPE</b></p>
<p>In this case, the basic model with no by-participant random slope,  no random intercepts and age as a covariate produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: disgust videos were more disgusting than losing points (<b>as predicted</b>)
<li>Fear videos, perhaps surprisingly, were significantly <b>less</b> disgusting than losing points
<li>There was also a significant negative effect of age
<p></p>
```{python}
#| label: Model G
#| echo: true

formula = 'disgusting_1~trial_type+prolific_age'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<p>The effects are unchanged when the age covariate is removed</p>
```{python}
#| label: Model G no covariate
#| echo: true

formula = 'disgusting_1~trial_type'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<p><b>MODEL H: FEAR ~ TRIAL_TYPE</b></p>
<p>In this case, the basic model with no by-participant random slope,  no random intercepts and age as a covariate produced the best fit (indexed by BIC scores).</p>
<li>This model found an effect of trial-type: fear videos were more frightening than losing points (<b>as predicted</b>)
<li>Disgust videos, perhaps surprisingly (but mirroring results from model H), were significantly <b>less</b> frightening than losing points
<li>There was also a significant negative effect of age
<p></p>
```{python}
#| label: Model H
#| echo: true

formula = 'frightening_1~trial_type+prolific_age'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<p>The effects are unchanged when the age covariate is removed</p>
```{python}
#| label: Model H no covariate
#| echo: true

formula = 'frightening_1~trial_type'

model=smf.mixedlm(formula, data, groups=data['participant_no'], missing='drop')
results=model.fit(reml=False)
print(results.summary())
```

<h3>Conclusions</h3>
<p>Results from these models tells us:</p>
<li>The stimulus selection procedure was unable to produce perfectly matched fear and disgust videos (with disgust videos being marginally more negatively valenced and fear videos being more arousing).
<li>There was a difference in habituation between fear and disgust (fear habituated less than disgust), which is in-line with previous literature.
<li>Fear and disgust videos reliably induced the emotions of fear and disgust (with fear videos producing much higher fear ratings and vice versa).
<li>The 'loss' feedback type (from the points conditions) was more similar to the emotional learning conditions than expected. It did not differ from fear in terms of valence and did not differ from disgust in terms of arousal.
<li>The 'loss' feedback type was, however, very different to the emotional conditions in terms of fear and disgust ratings. 
<p></p>